# redmine-plugin-work-report-exporter
# Copyright (C) 2022  Sutou Kouhei <kou@clear-code.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

.template:
  image: ruby:2.6
  parallel:
    matrix:
      - TESTS:
          - redmine:plugins:test:units
          - redmine:plugins:test:functionals
          - redmine:plugins:test:integration
          - redmine:plugins:test:system

sqlite3:
  extends: .template
  script:
    - dev/ci.sh sqlite3 $TESTS

postgresql:
  extends: .template
  services:
    - postgres:12.2
  variables:
    POSTGRES_DB: redmine
    POSTGRES_USER: redmine
    POSTGRES_PASSWORD: redmine
  before_script:
    - apt update -qq && apt install -y libpq-dev
  script:
    - dev/ci.sh postgresql $TESTS
