version: '3.1'
services:
  postgres:
    image: postgres:12.2
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine
      POSTGRES_DATABASE: redmine
      TZ: Asia/Tokyo

volumes:
  postgres:
